disabled = false
languageCode = 'hr-HR'
languageName = 'Hrvatski'
title = ''
copyright = """Designed with [Hugo](https://gohugo.io/)
 Licensed under [MIT license](https://github.com/ololiuhqui/magnolia-free-hugo-theme/blob/main/LICENSE.md) 游늯"""
contentDir = "content/hr"

[params]
  subtitle = "usluge obrade podataka"
  
  [params.homepage]
    preTitle = 'andalytics by'
    title = "marijana andabaka"
    intro= """
### R rje코enja za 코umarska istra쬴vanja
___

Napredne statisti캜ke analize i R rje코enja za 코umarska i ekolo코ka istra쬴vanja.
Kombiniranje doktorske ekspertize u 코umarstvu s analiti캜kim metodama za pretvaranje podataka u znanstvene uvide.

Podru캜ja ekspertize:
- **Statisti캜ka analiza i modeliranje** ekolo코kih i 코umarskih podataka
- **Integracija prostornih podataka** (GIS, remote sensing, terenska mjerenja)
- **R programiranje** za istra쬴va캜ke workflow-e
- **Analiza climate-forest interakcija**

Kao doktorica 코umarskih znanosti sa 7+ godina istra쬴va캜kog iskustva, razumijem i znanstvena pitanja i analiti캜ke izazove va코ih istra쬴vanja.
        """
    mainButton = "Usluge"
    mainButtonRef = "/usluge"
    secondButton = "Kontakt"
    secondButtonRef = "/kontakt"
    blogTitle = "R for Forest Science"
    blogButton= "More Posts"

[params.office]
  title = "R for Forest Science"
  description = "Insights on research data analysis, automation, and forest science"

[params.contacts]
  title = "Razgovarajmo o va코em istra쬴vanju"
  formCallToAction = "Po코aljite upit o va코em istra쬴va캜kom projektu"
  socialCallToAction = "Pove쬴te se sa mnom na profesionalnim mre쬬ma"
  [params.contacts.form]
    formspreeLink = "https://formspree.io/f/xrbezdlz"
    firstname = "Ime*"
    lastname = "Prezime*"
    email = "E-mail*"
    phone = "Telefon*"
    Inquiry = "Opi코ite svoje istra쬴va캜ke potrebe*"
    checkbox = "Prihva캖am obradu podataka u skladu s propisima o za코titi privatnosti*"
    submitBtn = "Po코alji upit"

[params.services]
  title = "Usluge Analize Podataka za 맛marska Istra쬴vanja"
  description = """Napredna statisti캜ka analiza i R rje코enja za 코umarska i ekolo코ka istra쬴vanja.
  
  Kombiniranje doktorske ekspertize u 코umarstvu s naprednim analiti캜kim metodama za pretvaranje slo쬰nih skupova podataka u korisne znanstvene uvide.""" 
  
  [params.services.list]
    [params.services.list.0]
      title = "Statisti캜ka analiza i modeliranje"
      description = "Napredni statisti캜ki pristupi za slo쬰ne ekolo코ke i 코umarske skupove podataka. Usluge uklju캜uju mixed-effects modeliranje, multivarijatnu analizu, analizu vremenskih nizova i prostornu statistiku. Razvijam metodolo코ki rigorozne analize koje odgovaraju na va코a specifi캜na istra쬴va캜ka pitanja, uzimaju캖i u obzir slo쬰nosti svojstvene ekolo코kim podacima. Sve analize osmi코ljene su za podr코ku peer-reviewed publikacijama i znanstvenom odlu캜ivanju."
    
    [params.services.list.01]
      title = "Integracija prostornih Podataka"
      description = "Integracija i analiza prostornih skupova podataka uklju캜uju캖i terenska mjerenja, remote sensing, GIS podatke i varijable okoli코a. Specijaliziram se za kombiniranje vi코e prostornih izvora podataka i rad s geografskim informacijama za potrebe 코umarskih istra쬴vanja."
   
   [params.services.list.02]
     title = "Utjecaj klime na 코umske ekosustave"
     description = "Analiza utjecaja klime na 코umske ekosustave koriste캖i integrirane klimatske i ekolo코ke skupove podataka. Usluge uklju캜uju climate change impact procjene, vulnerability analize i analizu dugoro캜nih trendova. Specijaliziram se za povezivanje klimatskih varijabli s odzivima 코uma, od rasta pojedinih stabala do promjena na razini ekosustava."
    
   [params.services.list.03]
     title = "Razvoj istra쬴va캜kog workflow-a"
     description = "Stvaranje reproducibilnih R workflow-a prilago캠enih va코im istra쬴va캜kim potrebama. Razvijam sveobuhvatne analiti캜ke procese koji osiguravaju metodolo코ku dosljednost i znanstvenu transparentnost. Usluge uklju캜uju custom R script development, automatizirane reporting sustave i training programe koji grade analiti캜ke kapacitete va코eg tima."
    
    [params.services.list.04]
      title = "Znanstvena vizualizacija i komunikacija"
      description = "Razvoj publication-quality vizualizacija koje u캜inkovito komuniciraju slo쬰ne istra쬴va캜ke rezultate. Usluge uklju캜uju naprednu statisti캜ku grafiku, interactive dashboards i data science aplikacije. Specijaliziram se za stvaranje vizualizacija koje ne samo zadovoljavaju publikacijske standarde ve캖 tako캠er pobolj코avaju znanstveno razumijevanje i olak코avaju istra쬴va캜ku komunikaciju."
[params.socials]
  enabled = true
  callToAction = "Pove쬴mo se na profesionalnim mre쬬ma >"
     [[params.socials.link]]
        name = "github"
        link = "https://github.com/andabaka"
      [[params.socials.link]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/marijana-andabaka/"
      [[params.socials.link]]
        name = "googlescholar"
        link = "https://scholar.google.hr/citations?user=awNSPV8AAAAJ&hl=en"

[params.schedules]
  enabledFooter = false
  enabledContacts = false
  title = "Radno vrijeme"
  [params.schedules.days]
    day1 = ""
    day2 = ""
    day3 = ""
    day4 = ""
    day5 = ""
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription1 = "Savjetovanje u podru캜ju obrade podataka za istra쬴va캜ke institucije"
  extraDescription2 = ""
  [params.footer.navigate]
  heading = "Navigacija"   
  [params.footer.contacts]
  enabled = true
  heading = "Kontakt"
  address = "Ivana Pintari캖a 30, 10290 Ivanec Bistranski, Hrvatska"
  mail = "marijana@andalytics.com"
  mail2 = ""
  phone = ""
  
[params.notfound]
  title = "404, stranica nije prona캠ena"

[params.single]
  similarContent= "Sli캜ni sadr쬬ji"
  toc= "Sadr쬬j"

[menus]
  [[menus.main]]
  name = "Po캜etna"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Usluge"
  pageRef = "pages/services"
  weight = 2
  [[menus.main]]
  name = "Blog"
  pageRef = "posts"
  weight = 3
  [[menus.main]]
  name = "Kontakt"
  pageRef = "pages/contacts"
  weight = 4