disabled = false
languageCode = 'hr-HR'
languageName = 'Hrvatski'
title = ''
copyright = """Designed with [Hugo](https://gohugo.io/)
 Licensed under [MIT license](https://github.com/ololiuhqui/magnolia-free-hugo-theme/blob/main/LICENSE.md) 游늯"""
contentDir = "content/hr"

[params]
  subtitle = "usluge obrade podataka"
  
  [params.homepage]
    preTitle = 'andalytics by'
    title = "marijana andabaka"
    intro= """
### Obrada podataka koja traje mjesecima? Zavr코ite je za nekoliko sati
___

Automatizacija analize podataka za znanstveno-istra쬴va캜ke institucije s posebnim fokusom na 코umarske znanosti. 
Podru캜ja ekspertize:
- **R programiranje** za automatizaciju istra쬴va캜kih procesa
- Analiza **istra쬴va캜kih podataka u 코umarstvu**
- Integracija **prostornih podataka**
- Obrada **klimatskih podataka**

Kao doktorica 코umarskih znanosti sa 7 godina akademskog istra쬴va캜kog iskustva, razumijem izazove obrade va코ih istra쬴va캜kih podataka.
        """
    mainButton = "Usluge"
    mainButtonRef = "/usluge"
    secondButton = "Kontakt"
    secondButtonRef = "/kontakt"
    blogTitle = "Blog Posts"
    blogButton= "More Posts"

[params.office]
  title = "Blog"
  description = "Uvidi u analizu podataka, automatizaciju i 코umarsku znanost"

[params.contacts]
  title = "Razgovarajmo o va코em istra쬴vanju"
  formCallToAction = "Po코aljite upit o va코em istra쬴va캜kom projektu"
  socialCallToAction = "Pove쬴te se sa mnom na profesionalnim mre쬬ma"
  [params.contacts.form]
    formspreeLink = "https://formspree.io/f/xrbezdlz"
    firstname = "Ime*"
    lastname = "Prezime*"
    email = "E-mail*"
    phone = "Telefon*"
    Inquiry = "Opi코ite svoje istra쬴va캜ke potrebe*"
    checkbox = "Prihva캖am obradu podataka u skladu s propisima o za코titi privatnosti*"
    submitBtn = "Po코alji upit"

[params.services]
  title = "Usluge obrade istra쬴va캜kih podataka"
  description = """Pretvaram slo쬰ne istra쬴va캜ke podatake u znanstveno upotrebljive rezultate. 
  Pru쬬m ekspertizu u 코umarskim znanostima uz podr코ku ostalim istra쬴va캜kim institucijama u automatizaciji obrade podataka."""
  [params.services.list]
    [params.services.list.0]
      title = "Automatizacija istra쬴vanja"
      description = "Pretvaram dugotrajnu ru캜nu obradu podataka u u캜inkovite automatizirane procese. Razvijam prilago캠ena rje코enja koja pojednostavljuju va코e istra쬴va캜ke procese uz odr쬬vanje strogih standarda kvalitete. Usluge uklju캜uju automatiziranu pripremu podataka, standardizaciju istra쬴va캜kih protokola, obradu velikih skupova podataka i izradu ponovljivih analiti캜kih postupaka. Ova automatizacija zna캜ajno smanjuje vrijeme analize i mogu캖nost ljudske pogre코ke, omogu캖uju캖i istra쬴va캜ima i znanstvenicima fokus na interpretaciju i otkri캖a."
    
    [params.services.list.01]
      title = "R programska rje코enja"
      description = "Razvoj prilago캠enih R skripti za va코e specifi캜ne istra쬴va캜ke izazove. Izra캠ujem cjelovita rje코enja koja uklju캜uju u캜inkovite procese obrade podataka, robusne funkcije za statisti캜ku analizu i dinami캜ke vizualizacije podataka. Svako rje코enje je izra캠eno s naglaskom na ponovljivost i dolazi s detaljnom dokumentacijom i trajnom podr코kom. Bez obzira radite li s vremenskim serijama, prostornim podacima ili slo쬰nim hijerarhijskim skupovima podataka, mogu vam pomo캖i pojednostaviti proces analize."
    
    [params.services.list.02]
      title = "Analiza podataka 코umarskih istra쬴vanja"
      description = "Sveobuhvatna analiti캜ka rje코enja za 코umarska istra쬴vanja koja kombiniraju podatke inventura, daljinskih istra쬴vanja i okoli코nih parametara. Usluge uklju캜uju obradu podataka 코umarskih mjerenja, analize rasta i prirasta stabala, procjenu zdravlja 코uma i pra캖enje ekosustava. Fokus na integraciji razli캜itih izvora podataka radi dubljeg uvida u dinamiku 코uma i njihove reakcije na promjene u okoli코u."
    
   [params.services.list.03]
     title = "Obrada prostornih podataka"
     description = "Napredna obrada i analiza prostornih podataka sa specijalizacijom za 코umarska istra쬴vanja. Usluge uklju캜uju rad s razli캜itim prostornim formatima, obradu satelitskih snimaka, integraciju terenskih mjerenja s podacima daljinskih istra쬴vanja, te razvoj automatiziranih postupaka prostorne analize. Posebna ekspertiza u analizi strukture 코uma i pra캖enju promjena kroz vrijeme pomo캖u naprednih geoprostornih metoda."
   
   [params.services.list.04]
      title = "Integracija klimatskih podataka"
      description = "Obrada i analiza klimatskih podataka u istra쬴va캜kom kontekstu. Usluge uklju캜uju integraciju klimatskih varijabli s terenskim mjerenjima, analize utjecaja klime na 코umske ekosustave, te razvoj automatiziranih sustava pra캖enja. Specijalizacija u povezivanju klimatskih podataka s razli캜itim aspektima 코umskih ekosustava, od rasta i vitalnosti stabala do dinamike sastojina i dugoro캜nih promjena u ekosustavima."
    
    [params.services.list.05]
      title = "Vizualizacija istra쬴vanja"
      description = "Izrada vizualizacija podataka prikladnih za publikacije koje u캜inkovito komuniciraju rezultate istra쬴vanja. Usluge uklju캜uju razvoj prilago캠enih funkcija za grafi캜ki prikaz, interaktivnih alata za vizualizaciju i automatiziranu izradu izvje코캖a. Specijalizacija u vizualizaciji slo쬰nih prostornih obrazaca, vremenskih trendova i vi코evarijabilnih odnosa. Sve vizualizacije su reproducibilne i lako se a쬿riraju novim podacima."

[params.socials]
  enabled = true
  callToAction = "Pove쬴mo se na profesionalnim mre쬬ma >"
     [[params.socials.link]]
        name = "github"
        link = "https://github.com/andabaka"
      [[params.socials.link]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/marijana-andabaka/"
      [[params.socials.link]]
        name = "googlescholar"
        link = "https://scholar.google.hr/citations?user=awNSPV8AAAAJ&hl=en"

[params.schedules]
  enabledFooter = false
  enabledContacts = false
  title = "Radno vrijeme"
  [params.schedules.days]
    day1 = ""
    day2 = ""
    day3 = ""
    day4 = ""
    day5 = ""
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription1 = "Savjetovanje u podru캜ju obrade podataka za istra쬴va캜ke institucije"
  extraDescription2 = ""
  [params.footer.navigate]
  heading = "Navigacija"   
  [params.footer.contacts]
  enabled = true
  heading = "Kontakt"
  address = "Ivana Pintari캖a 30, 10290 Ivanec Bistranski, Hrvatska"
  mail = "marijana@andalytics.com"
  mail2 = ""
  phone = ""
  
[params.notfound]
  title = "404, stranica nije prona캠ena"

[params.single]
  similarContent= "Sli캜ni sadr쬬ji"
  toc= "Sadr쬬j"

[menus]
  [[menus.main]]
  name = "Po캜etna"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Usluge"
  pageRef = "pages/services"
  weight = 2
  [[menus.main]]
  name = "Blog"
  pageRef = "posts"
  weight = 3
  [[menus.main]]
  name = "Kontakt"
  pageRef = "pages/contacts"
  weight = 4